services:
  nats:
    image: nats:latest
    container_name: nats

  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
  auth-ms:
    image: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}

  client-gateway:
    image: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_URL=${NATS_URL}

  inventory-ms:
    image: inventory-ms
    build:
      context: ./inventory-ms
      dockerfile: dockerfile.prod
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${INVENTORY_DB_URL}
      - PRODUCTS_MIN_ITEMS=${PRODUCTS_MIN_ITEMS}

  orders-ms:
    image: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    environment:
      - NATS_URL=${NATS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - DATABASE_URL=${ORDERS_DB_URL}

  payments-ms:
    image: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - NATS_URL=${NATS_URL}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - PAYMENT_PORT=${PAYMENT_PORT}
    ports:
      - ${PAYMENT_PORT}:${PAYMENT_PORT}

  products-ms:
    image: products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${PRODUCTS_DB_URL}
      - PRODUCTS_MIN_ITEMS=${PRODUCTS_MIN_ITEMS}
