services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    container_name: client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_URL=${NATS_URL}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev

  products-ms:
    build: ./products-ms
    container_name: products-ms
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${PRODUCTS_DB_URL}
      - PRODUCTS_MIN_ITEMS=${PRODUCTS_MIN_ITEMS}
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev

  inventory-ms:
    build: ./inventory-ms
    container_name: inventory-ms
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${INVENTORY_DB_URL}
      - PRODUCTS_MIN_ITEMS=${PRODUCTS_MIN_ITEMS}
    volumes:
      - ./inventory-ms/src:/usr/src/app/src
    command: npm run start:dev

  orders-db:
    image: postgres:16-alpine3.21
    container_name: orders-db
    environment:
      - POSTGRES_USER=${ORDERS_DB_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB_NAME}
    ports:
      - ${ORDERS_DB_PORT}:${ORDERS_DB_PORT}
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data

  orders-ms:
    build: ./orders-ms
    container_name: orders-ms
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${ORDERS_DB_URL}
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - orders-db

  auth-ms:
    build: ./auth-ms
    container_name: auth-ms
    environment:
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
